pkg/compiler/transformers/k8s/workflow.go
pkg/compiler/transformers/k8s/workflow_test.go
pkg/controller/nodes/executor_test.go
pkg/controller/nodes/node_exec_context.go
pkg/utils/k8s.go

We need this information so we can get pod level usage metrics for workflows. I will be adding a similar change later to plugins repo for array job.

Adding workflow name to workflow crd labels

---

boilerplate/lyft/golang_test_targets/Makefile
pkg/controller/nodes/task/resourcemanager/noop_resourcemanager.go
pkg/controller/nodes/task/resourcemanager/redis_resourcemanager.go
pkg/controller/nodes/task/resourcemanager/resourcemanager.go
pkg/controller/nodes/task/taskexec_context.go

Implementing cluster-namespaced redis set and project-namespaced token in resource manager

Cluster-namespaced redis set and project-namespaced allocation token [resource mgr]

---

boilerplate/lyft/pull_request_template/Readme.rst
boilerplate/lyft/pull_request_template/pull_request_template.md
boilerplate/lyft/pull_request_template/update.sh
boilerplate/update.cfg
pull_request_template.md

Adds a standardized pull request template from boilerplate
Added a new pull_request_template.md
https://github.com/lyft/flyte/issues/194
NA

Add Pull request template for FlytePropeller

---

pkg/controller/nodes/node_exec_context.go
pkg/controller/nodes/node_exec_context_test.go

Pass task-name and node-id in pod labels

---

Makefile

`;` would not fail CI if unit test fails.
Move unit test execution and coverage collection as two separated steps.
Note that this PR does NOT fix the offending test case(s).
NA
NA

fail ci if unit test fails

---

pkg/controller/nodes/subworkflow/subworkflow_test.go

This fixes the test case with improper stubbing.
As discussed in #89 , this is the offending test case. The problem I think is due to improper
stubbing.
NA
NA

fix failing test case

---

go.mod
go.sum

Bump FlytePlugins to v0.3.16 that enables NodeSelector and Tolerations configuration for k8s-array tasks
_NA_
OR

Bump plugins to v0.3.16

---

go.mod
go.sum

Update to latest flytePlugins. Especially to get the improved container error messaging.
Updated flyteplugins
https://github.com/lyft/flyte/issues/244
NA

Update Flyteplugins to v0.3.20

---

pkg/controller/handler.go

Adds a log line when a panic occurs in a round.
https://github.com/lyft/flyte/issues/269

Log when a panic occurs to make it easier to find in logs

---

codecov.yml

Adds a code coverage range
https://github.com/lyft/flyte/issues/283
NA

Code coverage Gate

---

go.mod
go.sum

Update Flyteplugins to latest v0.3.23
This enables end to end user vs system errors
https://github.com/lyft/flyte/issues/300
NA

Flyteplugins -> v0.3.23

---

pkg/controller/nodes/dynamic/handler.go
pkg/controller/nodes/task/handler.go
pkg/controller/nodes/task/k8s/plugin_manager.go
pkg/controller/nodes/task/k8s/plugin_manager_test.go

This reverts commit b18dca0a4f74dffc4d7ce9ecfc81a1cec016b49a.

Revert "Bug; abort fails for a task and running pods are not deleted(#139)"

---

pkg/controller/nodes/task/handler.go
pkg/controller/nodes/task/handler_test.go
pkg/utils/helpers.go
pkg/utils/helpers_test.go

In place of https://github.com/lyft/flyteplugins/pull/93

Add success and failure for Plugin metrics

---

go.mod
go.sum

Deploy the new version of flyteplugins
- [ x] Plugin
- [ x] Code completed
- [ x] Smoke tested
Update the latest version of the plugins
https://github.com/lyft/flyte/issues/344

Deploy the new version of flyteplugins

---

go.mod
go.sum

https://github.com/lyft/flyteplugins/releases/tag/v0.3.31
Bump
https://github.com/lyft/flyte/issues/348
NA

Plugins to 0.3.31

---

go.mod
go.sum

https://github.com/lyft/flyte/issues/347
https://github.com/lyft/flyteplugins/releases/tag/v0.3.32

Plugins 0.3.32

---

go.mod
go.sum

https://github.com/lyft/flyteplugins/releases/tag/v0.3.34

Reverting bad Presto pluging deployment

---

go.mod
go.sum

A lot of the fields in SageMaker CRDs are case sensitive, but only some of them are validated at CRD level. The bug this PR fixed was detected by the operator.
https://github.com/lyft/flyteplugins/pull/107
A lot of the fields in SageMaker CRDs are case sensitive, but only some of them are validated at CRD level. The bug this PR fixed was detected by the operator. We use strings.Title(strings.ToLower(<protoc enum>.String())) to fix it.
_NA_

[Bug fix] SageMaker CRD fields case sensitivity

---

.github/workflows/release.yaml
.goreleaser.yml
version/version.go
version/version_test.go

1. Goreleaser added for managing kubectl-flyte build and release.  
2. Github action added for releasing the binary 
3. Added version package 
https://github.com/lyft/flyte/issues/120
https://github.com/lyft/flyte/issues/120

release workflow added

---

go.mod
go.sum

[#patch] Bump plugins version to  v0.5.1

---

go.mod
go.sum

This PR updates the version of flyteidl in this repo.
Based on the discussion with Haytham, I've updated the version. This was discovered to be an issue when using the logger plugin (required updates to flyteidl are not reflected in the propellor).
_NA_
_NA_

Updated flyteidl version

---

go.mod
go.sum

Import the latest plugins to propeller

---

go.mod
go.sum

Import Latest plugins: Add interruptible support for Spark

---

.github/workflows/master.yml
.github/workflows/pull_request.yml

Migrate to github container registry.
https://github.com/lyft/flyte/issues/627

Push to Container Registry

---

pkg/controller/nodes/task/handler_test.go
pkg/controller/nodes/task/taskexec_context.go
pkg/controller/nodes/task/taskexec_context_test.go

Fix backward compatibility for task execution

Fix backward compatibility

---

pkg/controller/nodes/task/handler.go
pkg/controller/nodes/task/handler_test.go
pkg/controller/nodes/task/transformer.go

Handle nodeexec not found for Task

---

go.mod
go.sum

Brings in this PR: https://github.com/lyft/flyteplugins/pull/142
Please see the plugin PR.
https://github.com/lyft/flyte/issues/631
NA

Hive interpolation

---

.krew.yaml

Signed-off-by: Yuvraj <yuvraj.yad001@gmail.com>
Wrap krew description in 80 Char

Wrap krew description

---

README.md

Added docs for kube-flyte installation using krew  
_NA_
OR

Added krew installation docs

---

go.mod
go.sum
pkg/controller/nodes/task/catalog/datacatalog/datacatalog.go
pkg/controller/nodes/task/catalog/datacatalog/datacatalog_test.go
pkg/controller/nodes/task/catalog/datacatalog/mocks/DataCatalogClient.go
pkg/controller/nodes/task/catalog/datacatalog/transformer.go
pkg/controller/nodes/task/catalog/datacatalog/transformer_test.go

Remove the dependency from datacatalog and use the gen code from flyte idl
https://github.com/flyteorg/flyte/issues/827
_NA_
OR

Remove datacatalog deps

---

README.md

Updated the readme to add process of how to add new fields to CRD and generate the equivalent code for it.

Update op-code-generate process #patch

---

pkg/controller/nodes/subworkflow/launchplan.go

Nesting and principal are now filled in by flyteadmin.
https://github.com/flyteorg/flyte/issues/898
_NA_

Remove unused child workflow params

---

.github/config.yml
boilerplate/flyte/Readme.rst
boilerplate/flyte/config.yml
boilerplate/flyte/update.sh
boilerplate/update.cfg
boilerplate/update.sh

Signed-off-by: Samhita Alla <aallasamhita@gmail.com>
Update boilerplate.
_NA_
OR

Pull Boilerplate Code for Welcome Bot

---

pkg/compiler/transformers/k8s/node.go
pkg/compiler/transformers/k8s/workflow.go

Fixing branch nodes denormalization

---

pkg/controller/nodes/task/handler.go
pkg/controller/nodes/task/handler_test.go

Fixes https://github.com/flyteorg/flyte/issues/1049
https://github.com/flyteorg/flyte/issues/1049

Fix: register remaining tasks without default

---

go.mod
go.sum

Bump to pick up latest plugins
_NA_

Bump to pick up latest plugins

---

go.mod
go.sum

Updating to the latest version of flyteplugins

#minor Plugins update v0.5.52

---

cmd/controller/main.go
go.sum

https://github.com/flyteorg/flyte/issues/<number>
_NA_
OR

Add athena plugin

---

go.mod
go.sum

Bump plugins to pick up map support for pod tasks.
https://github.com/flyteorg/flyte/issues/1051
_NA_

Bump plugins to pick up map support for pod tasks.

---

go.mod
go.sum

Signed-off-by: wild-endeavor <wild-endeavor@users.noreply.github.com>
Pulling in https://github.com/flyteorg/flyteplugins/pull/183

Plugins - timestamp template fields

---

pkg/compiler/test/compiler_test.go
pkg/compiler/test/testdata/branch/5_myapp.workflows.cereal.mycereal_2.json
pkg/compiler/test/testdata/branch/compiled/5_myapp.workflows.cereal.mycereal_2.json
pkg/compiler/test/testdata/branch/compiled/mycereal_condition_has_no_deps.json
pkg/compiler/test/testdata/branch/compiled/success_3.json
pkg/compiler/test/testdata/branch/compiled/success_4.json
pkg/compiler/test/testdata/branch/compiled/success_5.json
pkg/compiler/test/testdata/branch/k8s/5_myapp.workflows.cereal.mycereal_2.json
pkg/compiler/test/testdata/branch/k8s/mycereal_condition_has_no_deps.json
pkg/compiler/test/testdata/branch/k8s/success_3.json
pkg/compiler/test/testdata/branch/k8s/success_4.json
pkg/compiler/test/testdata/branch/k8s/success_5.json
pkg/compiler/test/testdata/branch/mycereal_condition_has_no_deps.json
pkg/compiler/workflow_compiler.go

Do not add branch sub-nodes as downstream of any node. This prevents propeller from getting to these subnodes outside the context of executing branch nodes. At which point, it looks at the upstream nodes to ensure all required inputs are ready.
fixes https://github.com/flyteorg/flyte/issues/1205

Do not add downstream links for sub-branch-nodes

---

CODE_OF_CONDUCT.md
boilerplate/flyte/code_of_conduct/CODE_OF_CONDUCT.md
boilerplate/flyte/code_of_conduct/README.rst
boilerplate/flyte/code_of_conduct/update.sh
boilerplate/update.cfg

Signed-off-by: Samhita Alla <aallasamhita@gmail.com>
https://github.com/flyteorg/flyte/issues/1252
_- Make sure to use a concise title for the pull-request._
_- Use #patch, #minor or #major in the pull-request title to bump the corresponding version. Otherwise, the patch version
will be bumped. [More details](https://github.com/marketplace/actions/github-tag-bump)_
_NA_
OR

Update code of conduct

---

go.mod
go.sum

Bump plugins to pick up ephemeral storage changes
https://github.com/flyteorg/flyte/issues/494
_NA_

Bump plugins to pick up ephemeral storage changes

---

go.mod
go.sum

Update Flyteplugins to `v0.5.64` to apply this fix: https://github.com/flyteorg/flyteplugins/pull/197
_NA_
OR

Update flyteplugins to 0.5.64

---

go.mod
go.sum

- Bump new version of flytestdlib (Bug fix in storage)
_NA_
OR

bump flytestdlib version

---

go.mod
go.sum

Update flyteplugins to pull in: https://github.com/flyteorg/flyteplugins/pull/200
_NA_
OR

Bump flyteplugins to v0.5.68

---

go.mod
go.sum

Updates flyteplugin to v0.5.69 to pull in: https://github.com/flyteorg/flyteplugins/pull/204
_NA_
OR

Update flyteplugins to v0.5.69

---

go.mod
go.sum

Updates flyteplugins to pull in https://github.com/flyteorg/flyteplugins/pull/206/files
_NA_
OR

Update flyteplugins to v0.5.72

---

go.mod
go.sum

Bump Plugins that includes support for batchScheduler support in spark tasks
_NA_
OR

plugins v0.7.2

---

go.mod
go.sum

In https://github.com/flyteorg/flyteplugins/pull/222 we remove storage config from copilot pod spec. Just bump new flyteplugin version for changes. 
fixes https://github.com/flyteorg/flyte/issues/1782
_NA_
OR

bump: flyteplugins v0.7.5

---

go.mod
go.sum

Support for global pod security context
Refer to plugins PR https://github.com/flyteorg/flyteplugins/pull/223
fixes https://github.com/flyteorg/flyte/issues/1854
_NA_

Updated flyteplugins to support global pod security groups #patch

---

go.mod
go.sum

Update flyteplugins dependency to pickup fix for caching of subtasks
fixes https://github.com/flyteorg/flyte/issues/1609

Update flyteplugins to fix pickup k8s array plugin fix for caching

---

pkg/compiler/validators/bindings.go
pkg/compiler/validators/bindings_test.go
pkg/signals/signal_posix.go

Fix a panic (and improve the error) when SDK produces an empty binding
fixes https://github.com/flyteorg/flyte/issues/1935

Binding Panic when SDK produces an empty binding

---

README.md

Fix some format of relative link in README.md
_NA_
OR

Fix the relative link in README.md

---

pkg/compiler/validators/typing.go
pkg/compiler/validators/typing_test.go
pkg/compiler/validators/utils.go

- Add structured dataset type checker
- Update schema type checker
- Make schema compatible with the structured dataset
- Allow workflow to be like
- Upstream (structuredDatasetType) -> downstream (schemaType)
- Upstream (schemaType) -> downstream (structuredDatasetType)
https://github.com/flyteorg/flytekit/pull/785
_NA_

Add structured dataset type checker

---

.github/workflows/master.yml

Fixed release workflow for creating patch release from any branch
fixes https://github.com/flyteorg/flyte/issues/2080
_NA_
OR

Added workflow for patch release

---

.github/workflows/master.yml
.github/workflows/pull_request.yml

- Fix e2e pipeline for sandbox upgrade
fixes https://github.com/flyteorg/flyte/issues/2100
_NA_
OR

Fix e2e sandbox for upgrade

---

cmd/controller/cmd/root.go
cmd/controller/cmd/webhook.go
go.mod
go.sum
pkg/controller/nodes/task/setup_ctx_test.go

Metric name sanitization from flytestdlib.
_NA_

Pick latest flytestdlib with metric name sanitization

---

go.mod
go.sum

- Bump flyteplugins version to fix stow config bug https://github.com/flyteorg/flyteplugins/pull/250
fixes https://github.com/flyteorg/flyte/issues/2239
_NA_
OR

bump flyteplugins version

---

cmd/controller/main.go
plugins/loader.go

This facilitates a common package to manage all backend plugins loading
https://github.com/flyteorg/flyte/issues/2266
_NA_

Moving all plugins to a common package, for easy loading

---

cmd/controller/cmd/root.go
cmd/controller/cmd/webhook.go
pkg/controller/controller.go
propeller-config.yaml

Webhook in non single binary mode, will not startup

---

boilerplate/flyte/end2end/run-tests.py

Signed-off-by: Eduardo Apolinario <eapolinario@users.noreply.github.com>
Get ahead of the wave and bump boilerplate to not run the recently deprecated tests.
_NA_
OR

Bump boilerplate

---

go.mod
go.sum

Pulls in fix for Writing errors for subtask failures
_NA_

Update flyteplugins to v0.10.24

---

go.mod
go.sum
pkg/controller/completed_workflows.go
pkg/controller/completed_workflows_test.go
pkg/controller/garbage_collector.go
pkg/controller/garbage_collector_test.go

The condition for finding completed (terminated) workflows that are ready to be garbage collected is over constrained and therefore never finds any workflows. 
fixes https://github.com/flyteorg/flyte/issues/2400
https://github.com/flyteorg/flyte/issues/2396

GC: Fix condition for finding completed workflows #major

---

CODEOWNERS

I love reviewing code so much that I want to do more of it ...
^^^
_NA_
_NA_

Added myself to the CODEOWNERS file for default review on PRs

---

script/fold-logs.py

_- Make sure to use a concise title for the pull-request._
_- Use #patch, #minor or #major in the pull-request title to bump the corresponding version. Otherwise, the patch version
will be bumped. [More details](https://github.com/marketplace/actions/github-tag-bump)_
_NA_
OR

parse gcp formatted logs

---

.github/workflows/checks.yml
.github/workflows/upgrade_automation.yml
Dockerfile
go.mod
go.sum
pkg/compiler/typing/variable.go
pkg/compiler/validators/bindings_test.go
pkg/compiler/validators/typing.go
pkg/compiler/validators/typing_test.go
pkg/compiler/validators/utils.go
pkg/compiler/validators/utils_test.go

Treat empty lists/maps differently from how Void/None is treated. Empty lists/maps should be assignable to any lists/maps where as Void should only be assignable to NoneType...
fixes https://github.com/flyteorg/flyte/issues/2424

Empty lists/maps should match list/maps of any types

---

pkg/controller/nodes/task/catalog/datacatalog/datacatalog.go
pkg/controller/workflowstore/resource_version_caching_test.go

Signed-off-by: Prafulla Mahindrakar <prafulla.mahindrakar@gmail.com>
Slack conversation on the context
https://flyte-org.slack.com/archives/CNMKCU6FR/p1652437798343639
https://github.com/flyteorg/flyte/issues/2489
_NA_

Added grpc_client_handed_total prometheus metric for datacatalog

---

go.mod
go.sum

Updating the flyteplugins version to pickup support for external deletion on map task subtasks.
^^^
fixes https://github.com/flyteorg/flyte/issues/2701
_NA_

Support external deletion of non-terminal map task subtasks

---

go.mod
go.sum

https://github.com/flyteorg/flyteplugins/pull/286 update the snowflake endpoint. Here we update the flyteplugin version to pull the latest change.
^^^
https://github.com/flyteorg/flyteplugins/pull/286
_NA_

Updated flyteplugins version for snowflake plugin

---

go.mod
go.sum

bump flyteplugin version to address this [issue](https://flyte-org.slack.com/archives/CP2HDHKE1/p1667489853420529).
it will get rid of these warnings
```
{"json":{"exec_id":"abqczk9ch2lrjtb664th","node":"n0","ns":"flytesnacks-development","res_ver":"5554033","routine":"worker-2","tasktype":"python-task","wf":"flytesnacks:development:example_sd.wf"},"level":"warning","msg":"No plugin found for Handler-type [python-task], defaulting to [container]","ts":"2022-11-03T01:27:01Z"}
{"json":{"exec_id":"abqczk9ch2lrjtb664th","node":"n0","ns":"flytesnacks-development","res_ver":"5554039","routine":"worker-2","tasktype":"python-task","wf":"flytesnacks:development:example_sd.wf"},"level":"warning","msg":"No plugin found for Handler-type [python-task], …
```

bump flyteplugin version

---

go.mod
go.sum

Bumps flyteplugins version.
- `go get github.com/flyteorg/flyteplugins@v1.0.20 `
- `go mod tidy`
_NA_
OR

#patch flyteplugins to v1.0.20

---

go.mod
go.sum

Update flyteplugin version to pull the changes that adds podUID as an a new template variable
_NA_
OR

Update flyteplugin version to v1.0.27

---

go.mod
go.sum

Bump flyteplugins dependency to pick up [this PR](https://github.com/flyteorg/flyteplugins/pull/326).
^^^
_NA_
_NA_

bumping flyteplugins

---

go.mod
go.sum

Picks up external cluster configuration for Ray plugin.
^^^
_NA_
_NA_

Bumping flyteplugins to 1.0.42

---

pkg/controller/nodes/task/k8s/plugin_manager.go
pkg/controller/nodes/task/k8s/plugin_manager_test.go

See issue https://github.com/flyteorg/flyte/issues/3688 
_NA_
OR

Use correct k8 client

---

go.mod
go.sum

See title.
^^^
fixes https://github.com/flyteorg/flyte/issues/3694
_NA_

bumped flyteplugins to pickup dask resource fix

---

go.mod
go.sum

What it says on the can. Pulls in https://github.com/flyteorg/flyteplugins/pull/354

Bump flyteplugins to v1.0.63  # 

---

go.mod
go.sum

Update flyteplugins to v1.0.67

---

go.mod
go.sum

Updating flyteplugins to 1.1.8.
^^^
https://github.com/flyteorg/flyte/issues/3843
_NA_

Updating flyteplugins to 1.1.8

---

go.mod
go.sum

Fixes default resource configuration for the PyTorch Elastic plugin.
^^^
_NA_
_NA_

updated flyteplugins to 1.1.16

---

boilerplate/flyte/end2end/Makefile
boilerplate/flyte/end2end/end2end.sh
boilerplate/flyte/end2end/functional-test-config.yaml
boilerplate/flyte/end2end/run-tests.py

updating boilerplate to fix end2end tests
^^^
_NA_
_NA_

updating boilerplate to fix end2end tests

---

go.mod
go.sum

Update flyteplugins to pickup ray log links
fixes https://github.com/flyteorg/flyte/issues/4063

Ray log links
