- Gopkg.lock
- Gopkg.toml
Bumping versions to pick up Flyte IDL change deprecating Hive query collections.
https://github.com/lyft/flyteplugins/releases/tag/v0.1.2
https://github.com/lyft/flyteidl/releases/tag/v0.14.0
> Bump IDL/Plugins versions

- Gopkg.lock
Could not compile.  Apparently dep ensure doesn't update transitive dependencies.   This just runs `dep ensure -update`.
> github.com/dgrijalva/jwt-go was missing

- pkg/controller/catalog/datacatalog/datacatalog.go
The Catalog client is little too verbose when it errors. There are expected `NotFound` errors that we can downgrade to `debug`. Also the caller of the client logs errors so we don't need to explicitly do it in these cases.
> Adjust Catalog logs

- pkg/controller/handler.go
- pkg/controller/nodes/executor.go
- pkg/controller/nodes/task/handler.go
There are times when one workflow may take a longer than usual in a specific round. We emit a labeled metric so that we can segment metrics by the workflow id. We also try to capture the time spent in plugin invocation.
> Metrics captured for offending workflows

- cmd/controller/cmd/root.go
- pkg/controller/config/config.go
Kubeclient has a built in rate limiter to prevent browning out the server. 
We have added special configuration that allows controlling the number of requests from each propeller. This directly affects the throughput of Flyte (in terms of number of workflows) that can be executed. 
Caution: this is an advanced configuration and should be tuned carefully, to maintain stability of the API servers.
> Advanced options to configure kube client for large scale deployments

- pkg/controller/catalog/datacatalog/datacatalog.go
- pkg/controller/nodes/task/handler.go
Previously we were returning an error when the cache Tag already exists. This is a valid case when tasks with the same input run in quick succession, so it should not propagate an err.
> Clean up Cache stats

- pkg/compiler/validators/typing_test.go
- pkg/compiler/validators/utils.go
- For Scalar type Generic, the compiler was missing support. Added this support.
> Generic type support in Workflow compiler

- Gopkg.lock
- cmd/kubectl-flyte/cmd/root.go
It is already possible to use `kubectl flyte --kubeconfig ~/.kube/config get ...` connecting to a GKE cluster. This PR makes GCP auth supported natively so GKE users will not need to point to kube config manually.
> support GCP as auth provider

- Gopkg.lock
- Gopkg.toml
Bumping Flyteplugins to release 0.2.2 https://github.com/lyft/flyteplugins/releases/tag/v0.2.2
> bump flyteplugins version

- Gopkg.lock
- Gopkg.toml
https://github.com/lyft/flyteidl/releases/tag/v0.16.3
which needs a bump to plugins to
https://github.com/lyft/flyteplugins/releases/tag/v0.2.4
> Bump IDL to 0.16.3

- boilerplate/lyft/golang_test_targets/Makefile
- pkg/controller/nodes/executor.go
- pkg/controller/nodes/executor_test.go
- pkg/controller/nodes/task/handler.go
In cases where the abort call fails, we should still call finalize as this is the intended behavior of the finalize construct.
> Node executor abort to call finalize even on error

- pkg/controller/nodes/executor.go
- pkg/controller/nodes/task/k8s/plugin_manager.go
Subworkflows used in Dynamic Node Handler override GetNodeExecutionStatus function from the parent workflow, however Abort and Finalize were not using that override and were instead using GetExecutionStatus().GetNodeExecutionStatus(). This would only successfully retrieve nodes that are directly in the workflow as opposed to ones that are present as subnodes of another node.
> Fix invalid node lookup on abort/finalize

- Gopkg.lock
- Gopkg.toml
- pkg/controller/nodes/branch/handler.go
- pkg/controller/nodes/executor.go
- pkg/controller/nodes/executor_test.go
- pkg/controller/nodes/subworkflow/subworkflow.go
- pkg/controller/workflow/executor.go
1. Fixing the output directory path in admin event.
2. Fixing the retry attempt- should be called just when marking the node as running on a retry-able failure.
> Fixing the output dir in workflow event sent to Admin

- pkg/controller/nodes/dynamic/handler.go
- pkg/controller/nodes/dynamic/handler_test.go
Change the directory path used for subnodes to include the subnode retry attempt instead of the parent's attempt (that the previous commit added).
> Use sub-node retry attempt instead of parent node's

- .gitignore
- pkg/controller/nodes/dynamic/handler.go
- pkg/controller/nodes/dynamic/handler_test.go
- pkg/controller/nodes/task/handler.go
Bug: In a Dynamic Node, Finalize for parent node is never invoked. This happens in all cases of a dynamic node. When finalizers are uses, the finalize method becomes extremely important.
Fix: Finalize for parent node is always invoked when dynamic node is finalized
Corollary: Parent node is finalized when dynamic node is finalized, i.e., after all child nodes have completed. Child nodes get finalized as they complete independently.
> BugFix: Fix case in which Parent node in a Dynamic nodes finalize is not invoked

- pkg/controller/config/config.go
- pkg/controller/nodes/dynamic/handler.go
- pkg/controller/nodes/dynamic/handler_test.go
- pkg/controller/nodes/executor.go
- pkg/controller/nodes/executor_test.go
- pkg/controller/nodes/subworkflow/handler.go
- pkg/controller/nodes/subworkflow/launchplan.go
- pkg/controller/nodes/subworkflow/launchplan_test.go
- pkg/controller/nodes/subworkflow/subworkflow.go
- pkg/controller/nodes/subworkflow/subworkflow_test.go
https://github.com/lyft/flyte/issues/202
NA
> BugFix: SubWorkflow and dynamic node handling failure

- Makefile
- pkg/controller/config/config.go
- pkg/controller/config/config_flags.go
- pkg/controller/config/config_flags_test.go
- pkg/controller/nodes/executor.go
Declaring the type as `uint32` fails `go generate`. Change it to `int64`.
Changing it to `int64` to have the same range and cast it to `uint32` later.
Not sure this is the best option and hopefully system admins would not put a negative number.
NA
NA
> pflags does not support uint32

- pkg/controller/controller.go
- pkg/controller/garbage_collector.go
- pkg/controller/garbage_collector_test.go
No need to pass one additional argument because `cfg` has it.
This is not a bug or feature. The `namespace` argument is not necessary because it is read from `cfg` and `cfg` is already an argument.
NA
NA
> LimitNamespace is part of config

- pkg/controller/nodes/executor.go
We found metrics not reported. On further digging, we realized, that status is cleared in the Retry case, before we were using. Also in cases, few extra checks regarding node transitions prevented metrics from getting emitted.
- [X ] Bug Fix
- [ X] Code completed
- [ X] Smoke tested
> Emit error metrics for all failures

- pkg/controller/nodes/task/backoff/atomic_time.go
- pkg/controller/nodes/task/backoff/controller.go
- pkg/controller/nodes/task/backoff/handler.go
- pkg/controller/nodes/task/backoff/handler_test.go
- pkg/controller/nodes/task/k8s/plugin_manager_test.go
Backoff controller has two issues: 1) backoff() can overflow the exponent value leading to 0 backoff duration all the time. 2) There is a race condition in updating fields of the simple backoff handler. this PR should address both.
https://github.com/lyft/flyte/issues/233
> Fix exponent overflow

- pkg/controller/workflow/executor.go
Emit unlabeled metrics for Workflow success and Failure duration metrics. This enables computing overall system reliability metrics without having to sum individual wf metrics.
> Add unlabeled metrics for workflow success and failure durations

- Makefile
- boilerplate/lyft/golang_support_tools/tools.go
- boilerplate/lyft/golang_test_targets/Makefile
This change removes a target from the Makefile that's been added to the boilerplate golang test target Makefile.
https://github.com/lyft/flyte/issues/259
_NA_
> Update to latest boilerplate and remove duplicate codecov target

- pkg/controller/nodes/task/backoff/handler.go
- pkg/controller/nodes/task/backoff/handler_test.go
We saw that we weren't backing off in all cases where we should have been.  When resource quotas were at their limit for a namespace recently, we still saw the Pod K8s API server endpoint pegged at 8seconds.
Minor bug, no issue.
> Backoff also on TooManyRequests and ServerTimeout errors

- README.md
Godocs have moved, fixing the link
docs were pointing to the old godoc.org, changed it to pkg.go.dev
https://github.com/lyft/flyte/issues/258
> Docs point to the new godocs page

- pkg/controller/nodes/executor.go
Node timeout error should be tagged as an user error
https://github.com/lyft/flyte/issues/277
> Flyte node timeout is an usererror

- CODEOWNERS
Currently Flytepropeller allows anyone at Lyft to approve a code change. This can be detrimental and users should consult some people who have more understanding of the codebase
NA
NA
NA
> Restrict review access and commit access to few engineers

- cmd/controller/cmd/root.go
Reverts lyft/flytepropeller#63
I believe this PR is causing deploys to fail with
```
Error:
strict mode is on but received keys [map[add_dir_header:false alsologtostderr:false config:/etc/flyte/config*/config.yaml help:false log_backtrace_at::0 log_dir: log_file: log_file_max_size:1800 logtostderr:true skip_headers:false skip_log_headers:false stderrthreshold:2 v:0 vmodule:]] to decode with no config assigned to receive them: failed strict mode check
```
> Revert "pass command line args"

- pkg/controller/nodes/executor.go
- pkg/controller/nodes/executor_test.go
- pkg/controller/nodes/handler/transition_info.go
Default node timeout was not being correctly applied to the cases where node timeout specified in CRD was 0.
https://github.com/lyft/flyte/issues/289
> [Bug Fix] Node timeout should use default value if set to zero.

- pkg/controller/nodes/task/k8s/plugin_manager.go
- pkg/controller/nodes/task/k8s/plugin_manager_test.go
Implement Abort() on PluginManager to attempt to delete the created Resources (e.g. Pods, Spark Applications... etc.). This ensures that we do not wait for the GC to run to let K8s kill them saving resources from being wasted.
https://github.com/lyft/flyte/issues/263
> Delete K8s Resources on abort for K8s plugins

- pkg/controller/nodes/executor.go
We want to know the workflows that failed through user/system errors.
Unfortunately the way we are setup, this is not easy to achieve. I tried a number of options, and I believe almost everyone of them requires a significant refactor. I have implemented a version to gather opinion.
Alternate options tried:
1) Storing the Execution Error in Nodestatus: This involves replacing `error` with `executionError` - that unfortunately does not bode well in a lot of places, as we use `NodeErrorWithCause` and actually check if `e, ok := err.(*NodeError)`
2) Adding another field `execError` - This could be more confusing, as I do not know when to use which field.
https://jira.lyft.net/browse/MB-2251
> Emit User/System permanent error failures for Node

- pkg/controller/nodes/task/k8s/plugin_manager.go
- pkg/controller/nodes/task/k8s/plugin_manager_test.go
Abort in pluginmanager needs to add object metadata to be able to find and delete the object.
lyft/flyte#263
> Add missing objet metadata on abort

- pkg/apis/flyteworkflow/v1alpha1/error.go
- pkg/apis/flyteworkflow/v1alpha1/node_status.go
- pkg/apis/flyteworkflow/v1alpha1/node_status_test.go
ExecutionError is a nullable field. JSON marshal does not work with null values. This fix addresses this problem
NA
https://github.com/lyft/flyte/issues/300
NA
> Nullable field handling in CRD

- pkg/controller/handler.go
Add project/domain to context for metric labeling.
Added this line of code
```
ctx = contextutils.WithProjectDomain(ctx, wfDeepCopy.GetExecutionID().Project, wfDeepCopy.GetExecutionID().Domain)
```
NA
NA
> Add project/domain to context for metric labeling

- config.yaml
- pkg/controller/controller.go
- pkg/controller/controller_test.go
- pkg/controller/nodes/task/k8s/plugin_manager.go
First in a long series of work around Propeller observability and system observability as a whole.  Refer to the GH issue for more information.
* Create a new class that keeps a lister of FlyteWorkflow objects and periodically emits metrics about the list.
* Also changing the port for local development for Minio to reflect the new sandbox `NodePort`.
https://github.com/lyft/flyte/issues/311
NA
> Current level gauge for FlyteWorkflows

- pkg/controller/nodes/dynamic/handler.go
- pkg/controller/nodes/task/handler.go
- pkg/controller/nodes/task/k8s/plugin_manager.go
- pkg/controller/nodes/task/k8s/plugin_manager_test.go
Abort always fails for a task if task was already in a terminal state - success, failure or retryable fail. This is because the event publish fails.
This fix ensures an event is not published for terminal cases. 
NA
https://github.com/lyft/flyte/issues/333
NA
> Bug; abort fails for a task and running pods are not deleted

- pkg/controller/nodes/executor.go
- pkg/controller/nodes/executor_test.go
A regression was introduced, that would let abort be propagated for nodes that are not yet started.
Added checks and unit tests
https://github.com/lyft/flyte/issues/333
NA
> bug; abort called for not started nodes

- pkg/controller/nodes/task/config/config.go
- pkg/controller/nodes/task/config/config_flags.go
- pkg/controller/nodes/task/config/config_flags_test.go
- pkg/controller/nodes/task/handler_test.go
- pkg/controller/nodes/task/pre_post_execution.go
- pkg/controller/nodes/task/transformer.go
- pkg/controller/nodes/task/transformer_test.go
Containers can generate arbitrary large errors.pb files, this change protects propeller from accidentally loading a large errors.pb, saving it to etcd. and sending it to admin.
https://github.com/lyft/flyte/issues/334
> Trim error messages read from errors.pb to avoid spaming Etcd. and Admin

- pkg/controller/workflow/executor.go
- pkg/controller/workflow/executor_test.go
Abort can be initiated in 2 cases. Abort method now handles both the cases.
Case 1: User initiated. All retries are taken up
Case 2: System failure, atleast one retry is now available
NA
https://github.com/lyft/flyte/issues/309
NA
> bug; aborted workflows bubble up the error and stay in running

- pkg/controller/composite_workqueue.go
Everytime the object is re-enqueued to be processed, (in the K8s controller workqueue) it should be rate limited using any prior known conditions. For example, if a failure backoff is in effect it should be backed off, or if the bucketing is in effect, then the object should be throttled.
Using the RateLimitingInterface => https://godoc.org/k8s.io/client-go/util/workqueue#RateLimitingInterface method - AddRateLimited
https://github.com/lyft/flyte/issues/309
_NA_
> Workqueue should add items using a rate limiter

- go.mod
- go.sum
- pkg/controller/nodes/task/event_recorder_test.go
- pkg/controller/nodes/task/fakeplugins/next_phase_state_plugin.go
Bump Plugins Version + handle pluginCore.PhaseInfoInitializing inputs update.
https://github.com/lyft/flyte/issues/352
_NA_
OR
> Bump Plugins Version

- config.yaml
Update config.yaml to conform with the revised SageMaker official document
The SageMaker official document has been revised to recommend against the use of image tag `:latest` and `:1` for XGBoost, and has deprecated XGBoost 0.72 and the changed the image name from `xgboost` to `sagemaker-xgboost`. This PR updates the config file to conform with the official changes.
_NA_
> Update config.yaml to conform with the revised SageMaker official document

- pkg/controller/nodes/dynamic/dynamic_workflow.go
In cases where Propeller is responsible for fetching the definition of a launch plan from Admin, add the key to the log line.
> Amend log line

- pkg/compiler/errors/compiler_error_test.go
- pkg/compiler/errors/compiler_errors.go
- pkg/compiler/workflow_compiler.go
- pkg/compiler/workflow_compiler_test.go
Users frequently run into errors at runtime when no nodes are defined for a workflow graph but this can be caught at registration time to reduce confusion & iteration time.
https://github.com/lyft/flyte/issues/314
> Check for no nodes during workflow compilation

- .github/workflows/release.yaml
In the release, we are using the wrong tag formate. I replaced it with wildcard 
_NA_
OR
> Fix tag format #minor

- go.mod
- go.sum
- pkg/controller/nodes/task/handler.go
- pkg/controller/nodes/task/handler_test.go
- pkg/controller/nodes/task/transformer.go
- pkg/controller/nodes/task/transformer_test.go
Add TaskExecutionMetadata to TaskExecutionEvent. At this point this only captures whether a task on a spot node or not.
https://docs.google.com/document/d/1nqAp5-DanklNvG6OeQ3uIacZYGvf0oXioz7CboP_CsU/edit
https://github.com/lyft/flyte/issues/520
_NA_
> Add TaskExecutionMetadata to TaskExecutionEvent

- go.mod
- go.sum
This PR pulls in flyteidl 0.18.9 and flyteplugins 0.5.6 to add support for enabling MPI-based distributed training for SageMaker plugin
https://github.com/lyft/flyte/issues/452
> Adding support for enabling MPI-based distributed training for SageMaker plugin

- pkg/controller/nodes/task/handler_test.go
- pkg/controller/nodes/task/taskexec_context.go
- pkg/controller/nodes/task/taskexec_context_test.go
https://github.com/lyft/flyte/issues/469
> Add GetMaxAttempts() to taskExecutionMetadata

- .github/workflows/master.yml
- .github/workflows/pull_request.yml
- boilerplate/lyft/end2end/Makefile
- boilerplate/lyft/end2end/end2end.sh
- boilerplate/lyft/github_workflows/master.yml
- boilerplate/lyft/github_workflows/pull_request.yml
- Fixes docker caching key to use current SHA as the key with fallback from previous SHA and base SHA this ensures the docker cache gets persisted and make it available for subsequent builds
- Avoids rebuilding the image for each registry build by leveraging the cache
- Parallelizes a couple of steps that were serialized before
- Uses the same github workflow used in flyteadmin... paving the way to having a single source of truth in github.com/lyft/boilerplate of these workflows.
https://github.com/lyft/flyte/issues/579
> [Github workflows] Use latest boilerplate

- pkg/controller/nodes/dynamic/dynamic_workflow.go
- pkg/controller/nodes/task/handler.go
- pkg/controller/nodes/task/handler_test.go
- pkg/controller/nodes/task/taskexec_context.go
- pkg/controller/nodes/task/taskexec_context_test.go
- pkg/controller/nodes/task/transformer.go
- pkg/controller/nodes/task/transformer_test.go
The task events are still using older nodeId format even on the newer event version
> Fix node execution for tasks in new events

- pkg/compiler/validators/node.go
- pkg/compiler/validators/node_test.go
When a workflow has two nodes both of type WorkflowNodes and attempt to execute the same SubWF, the compiler attempts to compile the SubWorkflow twice (opportunity for optimization).. When it does the second time, it fails because validating Start and End nodes doesn't pass due to them not having targets (by design)... the fix is to handle start and end nodes specially...
The ultimate fix is to avoid compiling twice to begin with.
https://github.com/lyft/flyte/issues/633
> [Compiler] Compiling a compiled WF leads to compile errors

- pkg/controller/nodes/subworkflow/handler_test.go
- pkg/controller/nodes/subworkflow/launchplan.go
- pkg/controller/nodes/subworkflow/launchplan_test.go
For Launch plan, we reference to the parent executions node that kicked the launchplan. In this case, the nodeId was not replaced with the unique node id, and hence Admin was unable to find the node.
> Event Version Change for Launch plan Handler

- cmd/controller/cmd/root.go
Reverts lyft/flytepropeller#193
I'm not sure why this wasn't caught in the End-To-End tests but running Propeller in a cluster goes into a crashloop because of this change...
The error is:
```
strict mode is on but received keys [map[add_dir_header:false alsologtostderr:false config:/etc/flyte/config/*.yaml ginkgo:map[debug:false dryrun:false failfast:false failonpending:false flakeattempts:1 focus: nocolor:false noisypendings:true noisyskippings:true parallel:map[node:1 streamhost: synchost: total:1] progress:false randomizeallspecs:false regexscansfilepath:false reportfile: reportpassed:false seed:1611672198 skip: skipmeasurements:false slowspecthreshold:5 succinct:false trace:false v:false] help:false kubeconfig: log_backtrace_at::0 log_dir: log_file: log_file_max_size:1800 …
```
> Revert "Pass command-line arguments"

- cmd/kubectl-flyte/cmd/get.go
- config.yaml
- pkg/compiler/errors/compiler_errors.go
- pkg/compiler/validators/interface.go
- pkg/controller/config/config.go
- pkg/controller/handler.go
- pkg/controller/handler_test.go
- pkg/controller/nodes/dynamic/dynamic_workflow.go
- pkg/controller/nodes/task/fakeplugins/next_phase_state_plugin.go
- pkg/controller/workflow/executor.go
- pkg/controller/workflowstore/inmemory.go
This PR adds a new configuration to FlytePropeller which is enabled by default. This improves the transition latency of FlytePropeller by an order of magnitude or more. Absolute comparison to come soon.
Currently FlytePropeller event loop is designed to make the smallest forward progress in each round. There are cases in which the round progress is purely book-keeping. For example moving a workflow from accepted to Running state. Moving a node from new to queued to running state. This is done so that state is resilient from crashes.
the turbo mode, essentially waits for the one of these rounds to complete and optimistically progresses to the next round using the updated state. To add safety to the optimistic progress we can configure bounds.
The psuedo algorithm
```
w -> Original workflow …
```
> Introducing FlytePropeller TURBO Mode #minor

- go.mod
- go.sum
- pkg/controller/nodes/task/k8s/plugin_manager.go
- pkg/controller/nodes/task/k8s/plugin_manager_test.go
- pkg/controller/nodes/task/taskexec_context.go
This is an initial take on adding support for a custom KubeClient supplied by plugins. If `KubeClient` is added for a remote cluster we need to ignore `OwnerReferences`
@kumare3 @EngHabu let me know what you think. 
This will require https://github.com/flyteorg/flyteplugins/pull/154 and then a `flyteplugins` version bump
> Add support for custom KubeClient

- go.mod
- go.sum
- pkg/controller/nodes/task/handler.go
- pkg/controller/nodes/task/handler_test.go
- pkg/controller/nodes/task/k8s/plugin_manager.go
- pkg/controller/nodes/task/k8s/plugin_manager_test.go
- pkg/controller/nodes/task/taskexec_context.go
- pkg/controller/nodes/task/taskexec_context_test.go
Addresses part of flyteorg/flyte#858. needs rebase after https://github.com/flyteorg/flyteplugins/pull/167
https://github.com/flyteorg/flyte/issues/858
> Support GeneratedNameMaxLength property

- cmd/controller/cmd/root.go
- config.yaml
- go.mod
- go.sum
- pkg/controller/nodes/dynamic/handler.go
- pkg/controller/nodes/dynamic/mocks/task_node_handler.go
- pkg/controller/nodes/task/handler.go
- pkg/controller/nodes/task/pre_post_execution.go
- pkg/controller/nodes/task/taskexec_context.go
- pkg/controller/nodes/task/taskexec_context_test.go
This PR uses latest flyteplugins - pluginmachinery interface, that replaces a simple TaskReader with a TaskReader that has a path interface. The path method returns a deterministic path that can be passed to the actual container task to execute.
Depends on: https://github.com/flyteorg/flyteplugins/pull/166
https://github.com/lyft/flyte/issues/850
> Use the LazyUploadingTaskReader #minor

- go.mod
- go.sum
- pkg/controller/config/config.go
- pkg/controller/nodes/subworkflow/launchplan/admin.go
- pkg/controller/nodes/subworkflow/launchplan/admin_test.go
- pkg/controller/nodes/subworkflow/launchplan/adminconfig.go
- pkg/controller/workflowstore/config.go
- pkg/controller/workflowstore/iface.go
- Building a cache from Flyteadmin executions, should stop querying
flyteadmin, if the workflow is in terminal state
- Default for Max streak length can be optimized to 8 (number of rounds
needed to complete one workflow start to end, with inmemory execution)
- Other defaults set that have been hardened over time.
https://github.com/flyteorg/flyte/issues/882
> Bug Fix and Perf Tweak #minor

- pkg/compiler/errors/compiler_errors.go
- pkg/compiler/validators/bindings.go
- pkg/compiler/validators/bindings_test.go
The PR ensures that a bound value for Enums is valid at registration
/ compile time
https://docs.google.com/document/d/1rf0hMKbPebJ7jGYpsTDAbJ4ka58KIKD7EgWAEBIH06Q/edit#
https://github.com/flyteorg/flyte/issues/590
_NA_
> Compiler validates bound value for enum #patch

- go.mod
- go.sum
- pkg/controller/nodes/task/k8s/plugin_manager.go
- pkg/controller/nodes/task/k8s/plugin_manager_test.go
Implement DeleteResourceOnFinalize to delete k8s resources on Finalize() this ensures resources do not continue to consume cluster resources after flyte has detected they completed.
https://github.com/flyteorg/flyte/issues/1152
> Support DeleteResourceOnFinalize k8s plugin config

- go.mod
- go.sum
- pkg/compiler/transformers/k8s/node.go
- pkg/compiler/transformers/k8s/node_test.go
Implements node resource overrides.
Side note, we should find a good way to explore exposing these overrides to the user since the task spec in the console will only show the task resource requirements, rather than the resolved value.
https://github.com/flyteorg/flyte/issues/1170
_NA_
> Use node resource overrides

- .github/workflows/master.yml
- .github/workflows/pull_request.yml
Kind started failing to bring up CNI plugin and causing E2E tests to fail across all repos. We're not sure what caused this but something in the Github environment is probably to blame.
> Update kind to 0.11.1

- pkg/controller/nodes/core_phase.go
- pkg/controller/nodes/core_phase_test.go
- pkg/controller/nodes/executor.go
- pkg/controller/nodes/executor_test.go
- pkg/controller/nodes/task_event_recorder.go
- pkg/controller/nodes/task_event_recorder_test.go
- pkg/controller/workflow/executor.go
Task Events and node events can be sent as aborted, even if the task is completed. We should ignore these errors from admin.
Also workflow events if already exists should be ignored
https://github.com/flyteorg/flyte/issues/733
> FlytePropeller should ignore if Admin is already in terminal state #patch

- go.mod
- go.sum
- pkg/compiler/errors/compiler_errors.go
- pkg/compiler/task_compiler.go
- pkg/compiler/task_compiler_test.go
Now that pod specs are first class task template targets we should add some preliminary validation during compilation since we can reason about the expected object structure.
fixes https://github.com/flyteorg/flyte/issues/998
_NA_
> Add pod spec validation

- go.mod
- go.sum
Signed-off-by: wild-endeavor <wild-endeavor@users.noreply.github.com>
https://github.com/flyteorg/flyteplugins/pull/188
Bump plugins
> Plugins error document origin

- pkg/apis/flyteworkflow/v1alpha1/node_status.go
- pkg/apis/flyteworkflow/v1alpha1/node_status_test.go
When constructing a node status, the `DataDir` was incorrectly set to be a child of the parent's `DataDir` when it should have been a child of the parent's `OutputDir`.
This, incidentally, only broke in the case of Dynamic Workflow caching because in all other cases we explicitly set the data directory (essentially overriding the bad value retrieved from `GetNodeExecutionStatus`).
Further cleanup/refactor is needed to avoid having multiple branches of the code that set up data dir differently.
fixes https://github.com/flyteorg/flyte/issues/1238
> Construct subnode DataDir to be under parent's node OutputDir to keep behavior consistent across

- pkg/apis/flyteworkflow/v1alpha1/node_status.go
- pkg/apis/flyteworkflow/v1alpha1/node_status_test.go
Reverts flyteorg/flytepropeller#292
> Revert "Construct subnode DataDir to be under parent's node OutputDir to keep behavior consistent across"

- pkg/controller/nodes/executor_test.go
- pkg/controller/nodes/predicate.go
- pkg/controller/nodes/predicate_test.go
Downstream nodes of a node, have the parentNodeID always set. For the branch node, the parent node is the branch node of all the branches. When a sub-node of branch is to be executed, it should wait for the branch to be success, but the branch node (as it is the container node) will not be marked as success.
A branch sub-node may also be downstream from a regular node (e.g. start-node). Thus logically it can be executed after this node. But, it should wait for the branch condition to be evaluated and for the node to be ready.
fixes https://github.com/flyteorg/flyte/issues/1232
> Fix case in which downstream nodes may incorrectly fail because of parentNodeID #minor

- pkg/utils/k8s.go
- pkg/utils/k8s_test.go
Add ephemeral storage to node resource requirements. Otherwise, this is never used when building the container definition for the user task.
https://github.com/flyteorg/flyte/issues/494
_NA_
> Add ephemeral storage to node resource requirements

- go.mod
- go.sum
Signed-off-by: Jeev B <jeev.balakrishnan@freenome.com>
Bumps `flyteplugins` to `v0.5.63` to pull in fixes for sidecar/pod tasks resource requirement overrides.
_NA_
OR
> Bump flyteplugins to pull in sidecar resources fix

- pkg/controller/nodes/executor.go
Fix copy paste bug in recovering node exec inputs. We should only read from the execution data full inputs in the former if block when they are non-nil. In this else block we fetch the inputs by uri and download them before uploading them as the recovered node's inputs.
https://github.com/flyteorg/flyte/issues/1151
_NA_
> Fix copy paste bug in recovering node exec inputs

- pkg/controller/nodes/executor.go
Signed-off-by: Daniel Rammer <daniel@union.ai>
Changed the log level of node timeouts to info instead of error.
_TL;DR_
fixes https://github.com/flyteorg/flyte/issues/362
_NA_
> set node timeout log level to info

- go.sum
- pkg/controller/nodes/task/k8s/plugin_manager.go
A small change to how we log resource quantities to make them more readable.
Before the fix:
```
The resource requirement for creating Pod [cluster-deploy-development/c27it8qgli-n0-0] is [map[cpu:{{1 0} {\u003cnil\u003e}  DecimalSI} memory:{{524288000 0} {\u003cnil\u003e}  BinarySI}]]
```
After the fix:
```
The resource requirement for creating Pod [cluster-deploy-development/zvkuworvzn-n0-0] is [[{[cpu]: [1]} {[memory]: [500Mi]}]]
```
> Update logs to make resource quantities readable

- pkg/compiler/validators/node.go
- pkg/compiler/validators/node_test.go
When serializing workflows from flytekit (and other SDKs) there is no guarantee that node.UpstreamNodeIds will be ordered (in any consistent format). The ordering doesn't matter from the spec perspective since it doesn't dictate execution ordering. However, because it's an array/slice/list, when comparing the digest of the workflow being registered to those already registered, consistency in ordering matter. 
This PR alphabetically sorts the upstream_node_ids field of the node to ensure consistent ordering.
There is a caveat to the change from backward compatibility standpoint. If a user registers v1 of a workflow with descending (or random) ordering of upstream node ids, and then attempts to register the same spec again after …
> Order UpstreamNodeIds to ensure consistent compiler output

- go.mod
- go.sum
- pkg/controller/nodes/task/k8s/plugin_manager.go
- pkg/controller/nodes/task/k8s/plugin_manager_test.go
Per discussion in `#feature-discussions` Slack channel, I'm opening this as a draft PR as to center discussions related to flyteorg/flyte#1345.
This PR applies the `PluginCleanupPolicy` interface from flyteorg/flyteplugins#203, if applicable, instead of defaulting to just deleting the resource when the task is aborted.
this will need to be updated once the flyteplugins changed is merged & its version is bumped in `go.mod`.
cc @regadas , @EngHabu , @kumare3 :)
_NA_
OR
> Use PluginCleanupPolicy from flyteorg/flyteplugins#203

- pkg/controller/nodes/executor_test.go
- pkg/controller/nodes/transformers.go
Signed-off-by: Prafulla Mahindrakar <prafulla.mahindrakar@gmail.com>
The node data returned for start-node is currently incorrect from admin and this is due to the fact that propeller is sending non existent inputUri for  start-node
Flytekit gets around this issue by skipping the call to admin altogether and similar fix was done in flytectl 
https://github.com/flyteorg/flytekit/blob/master/flytekit/clis/flyte_cli/main.py#L1540
This is an attempt to fix the issue in propeller.
For start-node the Input and Output data is the same and hence using this fact we send the node event from propeller.
After the fix 
```
[
{
"node_exec": {
"id": {
"nodeId": "start-node",
"executionId": {
"project": "flytesnacks",
"domain": "development",
"name": "fdbbaa49c298c4bb48ad"
}
},
"closure": {
"outputUri": …
```
> Start-Node Output file copied to output result

- go.mod
- go.sum
- pkg/controller/handler.go
- pkg/controller/handler_test.go
- pkg/controller/nodes/errors/errors.go
- pkg/controller/workflow/errors/errors.go
- pkg/controller/workflow/executor.go
Signed-off-by: Daniel Rammer <daniel@union.ai>
Gracefully fail on ExecutionNotFound by transitioning the workflow the the 'FAILING' state. Subsequently, propeller will abort workflow tasks and transition the phase to 'FAILED'.
This facilitates graceful failures when experiencing an ExecutionNotFound error during workflow transitions. The error occurs when flyteadmin either doesn't have the provided workflow or the workflow is deleted. Either case is an invalid state and should result in the failure of the specified workflow.
We handle the race condition where flyteadmin, during the two phase execution, is between initializing the CRD and writing to the DB by checking if the workflow is in the 'READY' phase.
By transitioning the workflow to the 'FAILING' phase propeller will attempt to …
> gracefully failing workflow on ExecutionNotFound error

- Makefile
- go.mod
- go.sum
update flytestdlib version to support docs generate command (`flytepropeller config docs`)
https://github.com/flyteorg/flytestdlib/releases/tag/v0.4.4
_NA_
> Bump flytestdlib to v0.4.4

- events/admin_eventsink.go
- events/admin_eventsink_test.go
When the unique id is constructed for a task event, it should take into account the retry attempt
fixes https://github.com/flyteorg/flyte/issues/1824
_NA_
> Fix violated uniqueness constraint on task events

- events/errors/errors.go
- pkg/controller/nodes/executor.go
Workflows with large dynamic task fanouts can exceed the gRPC message size limit when reporting the compiled workflow closure as a NodeEvent. This PR captures such errors and immediately transitions the node, and consequently the workflow, to failing with the following error message:
`TooLarge: Event message exceeds maximum gRPC size limit, caused by [rpc error: code = ResourceExhausted desc = grpc: received message larger than max (5873232 vs. 4194304)]`
^^^
https://github.com/flyteorg/flyte/issues/1613
_NA_
> Gracefully fail when NodeEvent exceeds gRPC size limit

- events/admin_eventsink_integration_test.go
- events/errors/errors.go
- events/errors/errors_test.go
- go.mod
- go.sum
- pkg/controller/config/config.go
- pkg/controller/config/config_flags.go
- pkg/controller/config/config_flags_test.go
- pkg/controller/controller.go
- pkg/controller/handler.go
- pkg/controller/handler_test.go
- pkg/controller/nodes/executor.go
- pkg/controller/nodes/executor_test.go
- pkg/controller/nodes/handler_factory.go
- pkg/controller/nodes/task/handler.go
- pkg/controller/nodes/task/handler_test.go
- pkg/controller/nodes/task/transformer.go
- pkg/controller/nodes/task/transformer_test.go
- pkg/controller/nodes/task_event_recorder.go
- pkg/controller/nodes/transformers.go
- pkg/controller/workflow/executor.go
- pkg/controller/workflow/executor_test.go
At some point during workflow execution a scenario may arise when the cluster assigned to an execution is updated. This change introduces failure handling to early abort such workflows still running on the original cluster. IncompatibleCluster errors as they are first received are propagated to the workflow executor which transitions the workflow to failing to clean up resources. This leads to Abort handler calls for running tasks and nodes which swallow event recording failures due to subsequent (and expected) IncompatibleCluster errors.
Verified that the workflow CRD metadata ends up with `termination-status: terminated` for IncompatibleCluster errors sent initially for
- Workflow execution events
- Node execution events
- Task execution events 
- Subworkflows
- Child workflows
- Branch …
> Handle incompatible cluster events errors

- pkg/controller/nodes/task/handler.go
- pkg/controller/nodes/task/setup_ctx.go
- pkg/controller/nodes/task/setup_ctx_test.go
Creates a new metrics scope per plugin. This allows every plugin to create the same metrics if needed
fixes https://github.com/flyteorg/flyte/issues/2136
_NA_
> A new metrics scope per plugin is created

- pkg/compiler/validators/typing.go
- pkg/compiler/validators/typing_test.go
Upstream sd without column should be castable to sd with columns.
For example, the following task should be successfully compiled by the propeller. 
```python
@task
def to_numpy(ds: StructuredDataset) -> Annotated[StructuredDataset, cols, PARQUET]:
numpy_array = ds.open(np.ndarray).all()
return StructuredDataset(dataframe=numpy_array)
```
@task
def t1()
https://github.com/flyteorg/flyte/issues/2074
_NA_
> StructuredDataset without column should be castable to StructuredDataset with columns

- go.mod
- manager/manager.go
- manager/manager_test.go
Instead of initializing managed pods with a new ObjectMeta this PR resuses the ObjectMeta on the PodTemplate. This means that all managed FlytePropeller pods will adhere as closely to the original PodTemplate as possible, meaning labels, annotations, etc are set correctly.
This approach is proposed as an alternative to https://github.com/flyteorg/flytepropeller/pull/410.
^^^
_NA_
_NA_
> Use PodTemplate metadata in managed Pods

- go.sum
- pkg/controller/controller_test.go
- pkg/controller/nodes/executor.go
- pkg/controller/nodes/executor_test.go
SetMetricKeys needs to be done once per process. Removing the extra set
https://github.com/flyteorg/flyte/issues/2266
_NA_
> Remove extra SetMetricKeys

- pkg/controller/controller.go
- pkg/controller/garbage_collector.go
The PR applies the label selectors for sharded propeller to the garbage collector as well as the FlyteWorkflow CRD informer. This means that each individual sharded FlytePropeller instance will only garbage collect for FlyteWorkflows that it is responsible for executing.
^^^
fixes https://github.com/flyteorg/flyte/issues/2532
_NA_
> Restrict garbage collection with sharded propeller

- cmd/controller/cmd/root.go
- cmd/controller/cmd/webhook.go
- cmd/controller/main.go
- pkg/controller/config/config.go
- pkg/controller/config/config_flags.go
- pkg/controller/config/config_flags_test.go
This PR allows manually configuring prometheus metric labels using metric keys. Currently FlytePropeller default metric keys include the workflow and task IDs. This means that as the number of workflows / tasks increases the cardinality of metrics will increase as well. For some deployments this is undesirable. By enabling manual configuration we can tweak metric cardinality to satisfy deployment requirements.
^^^
fixes https://github.com/flyteorg/flyte/issues/2565
_NA_
> Make metric keys configurable

- pkg/controller/nodes/executor.go
- pkg/controller/nodes/executor_test.go
Currently FlytePropeller [calls "finalize"](https://github.com/flyteorg/flytepropeller/blob/b9fb6e31eeb27a15c522995b0c0ea0f5536c0fe0/pkg/controller/nodes/executor.go#L662) rather than "abort" on permanent failures. Consequently, during instances where a resource is actively running we fail to abort it. For example when the number of [timeouts](https://github.com/flyteorg/flytepropeller/blob/b9fb6e31eeb27a15c522995b0c0ea0f5536c0fe0/pkg/controller/nodes/executor.go#L389-L393) exceeds the maximum number of retries we [automatically transition](https://github.com/flyteorg/flytepropeller/blob/b9fb6e31eeb27a15c522995b0c0ea0f5536c0fe0/pkg/controller/nodes/executor.go#L397-L405) from a retryable failure to a permanent failure.
I do not believe there are any unintended side-effects by calling …
> Calling abort rather than finalize on permanent failure

- pkg/controller/nodes/subworkflow/launchplan/admin.go
When executing a launchplan that does not exist propeller checks if the `err != nil` before checking if the `lp == nil` [here](https://github.com/flyteorg/flytepropeller/blob/d3bef3c3c01127b9321e075ae84c2b27d598cd8a/pkg/controller/nodes/subworkflow/launchplan/admin.go#L154-L160). So when the launchplan doesn't exist it returns a `RemoteSystemError` which uses backoff retries rather than failing right away as a user error would. This PR checks the gRPC status code to correctly label the launchplan NotFound.
^^^
fixes https://github.com/flyteorg/flyte/issues/2404
_NA_
> GetLaunchPlan checks for NotFound gRPC code rather than nil launchplan

- pkg/controller/handler.go
- pkg/controller/handler_test.go
- pkg/controller/nodes/executor.go
- pkg/controller/nodes/task/handler.go
- pkg/controller/workflow/executor.go
Updating the workflow abort pipeline to drop ExecutionNotFound errors. Previously, this solution could handle workflows that have not yet started, but for those that are already executing the events that are sent as part of aborting the workflow triggered a cycle.
^^^
fixes https://github.com/flyteorg/flyte/issues/2275
_NA_
> Graceful failure on ExecutionNotFound error

- go.mod
- go.sum
This PR pulls the fix from flytestdlib. The issue is that Golangs `append` implementation may modify the underlying array. So when we use this to compute metric labels, we have the ability to corrupt the underlying array meaning other metrics will fail.
^^^
https://github.com/flyteorg/flyte/issues/2597
_NA_
> Fix prometheus metric panic when using additional labels

- pkg/controller/nodes/task/handler.go
https://flyte-org.slack.com/archives/CP2HDHKE1/p1659445048597709
`tCtx.ow.GetReader()` is nil when running map task or BigQuery task with no output. so we should add nil check for it.
_NA_
> Add nil check for output reader

- pkg/controller/controller.go
- pkg/controller/nodes/task/k8s/plugin_manager.go
Currently the subqueue in in the workflow queue is not working. This means that Flyte workflows are not enqueued when we detect changes in node status'. Enabling this will result in significant performance improvements.
^^^
_NA_
_NA_
> Enabled workqueue subqueue additions

- pkg/controller/handler.go
- pkg/controller/handler_test.go
Signed-off-by: Babis Kiosidis <ckiosidis@gmail.com>
```
goroutine 1299 [running]:
github.com/flyteorg/flytepropeller/pkg/controller.(*Propeller).Handle(0xc0010bcf00, {0x29ee0d8, 0xc2188e2720}, {0xc0009b8140, 0x12}, {0xc0009b8153, 0x8})
/go/pkg/mod/github.com/flyteorg/flytepropeller@v1.1.28/pkg/controller/handler.go:251 +0xd76
github.com/flyteorg/flytepropeller/pkg/controller.(*WorkerPool).processNextWorkItem.func1(0xc001024870, 0xc1f8f1ff28, {0x1ff6080?, 0xc000cbeec0})
/go/pkg/mod/github.com/flyteorg/flytepropeller@v1.1.28/pkg/controller/workers.go:88 +0x510
github.com/flyteorg/flytepropeller/pkg/controller.(*WorkerPool).processNextWorkItem(0xc001024870, {0x29ee0d8, 0xc2188e2720})
/go/pkg/mod/github.com/flyteorg/flytepropeller@v1.1.28/pkg/controller/workers.go:99 +0xf1 …
```
> avoid interacting with nil mutatedWfs

- pkg/compiler/validators/typing.go
- pkg/compiler/validators/typing_test.go
For more detail, check https://github.com/flyteorg/flyte/issues/2864
Failed to run BQ task when the cache is enabled because [type validation](https://github.com/flyteorg/flytepropeller/blob/9cf5368793e5d60113cb819a6e496a7b6accd619/pkg/compiler/validators/typing.go#L157) is failing.
In some cases, the expected type is empty but the input type has value, so skip the format check when the expected format is empty
When the expected format of SD is empty, the dataframe will be converted to a specific format determined by the SD transformer.
^^^
^^^
_NA_
> Skip the structured dataset format check when the expected format is empty

- go.mod
- go.sum
Updating FlytePropellers FlytePlugins dependency version to pull the latest updates to the default PodTemplate configuration. This allows containers named "default" and "primary" to serve as the base configuration for all respective containers that Flyte constructs.
^^^
https://github.com/flyteorg/flyte/issues/2703
_NA_
> Updated flyteplugins version for default container configuration

- cmd/controller/cmd/root.go
- cmd/controller/cmd/webhook.go
In networking setups where k8s requires Pods serving webhooks to have `hostNetwork: true` deployments may suffer "unable to bind address :8080" in the flyte-pod-webhook deployment. This is because both flytepropeller and the pod-webhook pods use the k8s controller-runtime manager internally to manager k8s informers, caches, etc. A component of the controller-runtime manager is the metrics server, which serves prometheus metrics. In the above scenario, if the flytepropeller and pod-webhook pods are deployed on the same host there will be collisions. This PR disables the controller-runtime manager metrics server.
^^^
fixes https://github.com/flyteorg/flyte/issues/2974
https://github.com/flyteorg/flyte/issues/2975 - we should serve the k8s controller-runtime manager metrics using …
> disable k8s controller-runtime manager metrics server

- pkg/webhook/init_cert.go
The value for the secret namespace for settings is grabbed dynamically.
Before:
A hardcoded string was used for setting the secret namespace
After:
The value for the secret namespace for settings is grabbed dynamically.
Signed-off-by: Francisco J. Solis <siscomagma@gmail.com>
fixes [https://github.com/flyteorg/flyte/issues/<number>
](https://github.com/flyteorg/flyte/issues/2968)
> fix: Add servicename in certs

- pkg/controller/workflowstore/config.go
- pkg/controller/workflowstore/factory.go
- pkg/controller/workflowstore/passthrough.go
- pkg/controller/workflowstore/resource_version_caching.go
- pkg/controller/workflowstore/resource_version_caching_test.go
- pkg/controller/workflowstore/terminated_tracking.go
- pkg/controller/workflowstore/terminated_tracking_test.go
- Move logic to [clear managed fields from the CRD](https://github.com/flyteorg/flytepropeller/pull/344) from the **resource version caching workflowstore** to the **passthrough workflowstore**
- Move logic to [track terminated workflows](https://github.com/flyteorg/flytepropeller/pull/450) from the **resource version caching workflowstore** to a new **terminated tracking workflowstore**
- The logic to [clear managed fields from the CRD](https://github.com/flyteorg/flytepropeller/pull/344) was moved to the **passthrough workflowstore** (the base workflowstore) since it seems like a core behavior that all workflowstores should have.
- The logic to [track terminated workflows](https://github.com/flyteorg/flytepropeller/pull/450) was moved to a new **terminated tracking workflowstore** …
> Move workflowstore logic to correct abstraction

- boilerplate/flyte/end2end/run-tests.py
Updating boilerplate to increase the number of MAX_ATTEMPTS in the end2end tests. Currently, some [PRs](https://github.com/flyteorg/flytepropeller/actions/runs/3532497687/jobs/5993995509) are blocked on timeouts.
^^^
_NA_
_NA_
> updating end2end tests from boilerplate

- pkg/controller/nodes/executor.go
Check that the DeckURI is not empty (ie. "") before querying the DataStore for file existence. This mitigate issues when querying for an empty file.
^^^
https://github.com/flyteorg/flyte/issues/3114
https://github.com/flyteorg/flyteconsole/issues/642
> Check deck uri exists before checking for datastore existance

- pkg/controller/nodes/gate/handler.go
The `LastAttemptStartedAt` is only populated on the `NodeStatus` during transition from `Queued` to `Running` phases. So the first time the GateNode handler evaluates the node it will be nil. This causes a panic when validating the sleep duration. This PR ensures this value is not nil when checking the sleep duration.
^^^
_NA_
_NA_
> Fixed nil panic on gate node sleep check

- go.mod
- go.sum
- pkg/controller/nodes/task/k8s/plugin_manager.go
Currently the k8s plugin default labels will override those manually set. This PR updates the k8s plugin manager to prefer labels set on the Pod definition over those specified on the defaults k8s plugin configuration.
^^^
_NA_
_NA_
> Fix issue where k8s plugin default labels override those set on pod

- pkg/compiler/validators/bindings.go
- pkg/compiler/validators/interface.go
- pkg/compiler/validators/interface_test.go
Currently, the `ApproveCondition` uses an empty node interface for validating variable bindings. This is incorrect, and results in a compilation failure. This PR uses upstream node bindings to discover the interface for the gate node in the case of an `ApproveCondition`.
^^^
https://github.com/flyteorg/flyte/issues/208
_NA_
> Fix gate node approve condition node interface binding validation 

- plugins/loader.go
Signed-off-by: Kevin Su <pingsutw@gmail.com>
Add `TensorFlow` to loader.go, so we can load `TensorFlow` plugin while starting the propeller.
^^^
https://flyte-org.slack.com/archives/C045P7GBGBU/p1673314641468229
_NA_
> Add TensorFlow to loader.go

- pkg/webhook/init_cert.go
Directories should not be made with 644.  Add a new perm just for mkdir.
> Use folder perm for making folder

- go.mod
- go.sum
Updates `flyteplugins` from `1.0.34` to `1.0.37` to pull in the change from https://github.com/flyteorg/flyteplugins/pull/315.
> Update flyteplugins to 1.0.37

- pkg/controller/nodes/executor.go
If an already recovered workflow was recovered again, all tasks were re-run.
This marks not only successful but also already recovered tasks as recoverable for futher runs.
See slack discussion: https://flyte-org.slack.com/archives/CP2HDHKE1/p1677245731470789
_NA_
_NA_
> fix recovery of already recovered workflow

- pkg/controller/executors/mocks/node_lookup.go
- pkg/controller/executors/node_lookup.go
- pkg/controller/executors/node_lookup_test.go
- pkg/controller/nodes/branch/handler.go
- pkg/controller/nodes/branch/handler_test.go
- pkg/controller/nodes/dynamic/dynamic_workflow.go
- pkg/controller/nodes/subworkflow/subworkflow.go
- pkg/controller/workflow/executor.go
Adding the `DAG` to `NodeExecutionContext` so that we can maintain upstream dependencies during BranchNode subnode executions.
Read the issue for more context.
fixes https://github.com/flyteorg/flyte/issues/3512
_NA_
> Including all upstream node deps on BranchNode subnode execution

- go.mod
- go.sum
- pkg/controller/nodes/task/k8s/plugin_context.go
- pkg/controller/nodes/task/k8s/plugin_manager.go
- pkg/controller/nodes/task/k8s/plugin_manager_test.go
Persisting k8s plugin state by embedding it in the overall state stored for all k8s plugins. The exporting the `PluginStateReader` function through the `PluginContext` so that k8s plugin writers can retrieve plugin state the same way they do in other plugins, just that persistend (ie. `PluginStateWriter`) is performed underneath.
^^^
fixes https://github.com/flyteorg/flyte/issues/3440
_NA_
> persisting k8s plugin state between evaluations

- pkg/webhook/config/config.go
- pkg/webhook/config/config_flags.go
- pkg/webhook/config/config_flags_test.go
- pkg/webhook/config/secretmanagertype_enumer.go
- pkg/webhook/gcp_secret_manager.go
- pkg/webhook/gcp_secret_manager_test.go
- pkg/webhook/secrets.go
Tested with:
```
from flytekit import Secret, task, workflow
@task(secret_requests=[Secret(group="mainsecret", key="na", group_version="1")])
def secret_task() -> str:
with open("/etc/flyte/secrets/mainsecret/1") as f:
return f.read()
@workflow
def wf() -> str:
x = secret_task()
return x
```
Note the use of the required `key`, even though the secrets plugin does not use it. @wild-endeavor: we may want to consider making this optional. Flytekit will also need support for including the group version [in the file path](https://github.com/flyteorg/flytekit/blob/6c52297ae65914bec5988e6fbae0a20fa9917599/flytekit/core/context_manager.py#L356) when fetching secrets.
> Add support for GCP secret manager

- cmd/controller/cmd/webhook.go
- pkg/webhook/entrypoint.go
This PR moves starting the controller-runtime manager outside of the webhook `Run` function. This is useful to ensure the controller-runtime manager starts in single binary even if the webhook is disabled.
^^^
https://github.com/flyteorg/flyte/issues/3546
_NA_
> Moved controller-runtime start out of webhook Run function

- pkg/controller/nodes/executor.go
[The PR](https://github.com/flyteorg/flytepropeller/pull/518) to enable recovering dynamic workflows when they have already compiled the workflow closure updated the node executor to [always use the phase returned](https://github.com/flyteorg/flytepropeller/blob/7ff7f96cd35c8e5ae0eb9a1a22b769c7f9930530/pkg/controller/nodes/executor.go#L385) from `attemptRecovery`. This [surfaced an issue where nodes](https://github.com/flyteorg/flytepropeller/blob/986f014ae69505353833c20a38d4a58094b800cc/pkg/controller/nodes/executor.go#L218-L219) in the `SKIPPED` phase were reported as `SKIPPED` during recovery when they should be executed in the recovered workflow.
This PR correctly reports the phase of previously `SKIPPED` nodes as `UNDEFINED` to ensure the nodes are correctly evaluated during workflow …
> Fixing recovering of SKIPPED nodes

- go.mod
- go.sum
- pkg/compiler/transformers/k8s/node.go
- pkg/compiler/transformers/k8s/node_test.go
- pkg/compiler/transformers/k8s/utils.go
Remove resource injection on the node for container task
In [BuildRawContainer](https://github.com/flyteorg/flyteplugins/blob/master/go/tasks/pluginmachinery/flytek8s/container_helper.go#L213), we do not inject the container resource from the  task template. Instead, we inject the resource from [parameters.TaskExecMetadata.GetOverrides().GetResources()](https://github.com/flyteorg/flytepropeller/blob/master/pkg/compiler/transformers/k8s/node.go#L49).
This is because for both `_with_override(resource=...` and `@task(requests=...)`, they are both inject as the node resource override in [buildNodeSpec](https://github.com/flyteorg/flytepropeller/blob/master/pkg/compiler/transformers/k8s/node.go#L49)
For the case of …
> Remove resource injection on the node for container task

- go.mod
- go.sum
Pulls the changes from this PR into flytepropeller to reduce Flyte overhead on k8s Pod executions. Basically, we rarely need to wait for the entire`Pod` to complete, rather once the primary container (or all containers) complete we can prematurely mark the task as successful. This mitigates time for the `Pod` operator to detect container completion and mark the `Pod` as completed. 
^^^
_NA_
_NA_
> Setting primaryContainerName by default on Pod plugin

- pkg/controller/nodes/subworkflow/launchplan.go
- pkg/controller/nodes/subworkflow/launchplan/admin.go
- pkg/controller/nodes/subworkflow/launchplan/launchplan.go
The `Interruptible` and `OverwriteCache` flags should be maintained through the `ExecutionSpec` when running reference launchplans in from a workflow.
^^^
fixes https://github.com/flyteorg/flyte/issues/3550
_NA_
> Maintaining Interruptible and OverwriteCache for reference launchplans

- pkg/webhook/config/config.go
- pkg/webhook/utils.go
- pkg/webhook/vault_secret_manager.go
- pkg/webhook/vault_secret_manager_test.go
Removes the KV Version config parameter and instead uses the Secret `group` field to allow using both (and other Vault secret backends) dynamically. 
This also allows using the [Database Secrets Engine](https://developer.hashicorp.com/vault/docs/secrets/databases), which effectively means noop since we want to read the whole credential and not just a specific key.
[The Secret protobuf defines a group field](https://github.com/flyteorg/flyteidl/blob/master/protos/flyteidl/core/security.proto#L33) which we have previously ignored. Leveraging that field allows to simplify the secret manager config and allows supporting multiple Vault secret backends dynamically by deciding what secret template to inject based on the optional `group` parameter.
This is a breaking change for people using the …
> Use group attribute for KV version and add DB engine support

- pkg/controller/nodes/subworkflow/launchplan/admin.go
Correctly checking the event code of an error to abort launchplan
^^^
fixes https://github.com/flyteorg/flyte/issues/3582
_NA_
> Correctly validating error code on aborting terminal launchplans

- pkg/controller/nodes/subworkflow/launchplan.go
- pkg/controller/nodes/subworkflow/launchplan/admin.go
- pkg/controller/nodes/subworkflow/launchplan/launchplan.go
Using the environment variables from the `ExecutionConfig` as defaults for all launchplans started from the execution.
^^^
fixes https://github.com/flyteorg/flyte/issues/3770
_NA_
> Propagating environment variables through launchplans

- .goreleaser.yml
Produce archives using the recommended alternative for archives.replacements
`archives.replacements` was deprecated and removed in the latest goreleaser version as per https://goreleaser.com/deprecations/#archivesreplacements. This PR follows the recommendation to use `name_template` to get the same effect.
I removed the unused `{{ .Arm }}` block also.
_NA_
OR
> Fix usage of archive replacements

- go.mod
- go.sum
Fix docs generation by using flytestdlib@1.0.19
I tested it locally compiling propeller locally and running:
```
❯ ./bin/flytepropeller config docs | grep -A1 Gke
...
gke-task-workload-identity (`google.GkeTaskWorkloadIdentityTokenSourceFactoryConfig`_)
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
--
google.GkeTaskWorkloadIdentityTokenSourceFactoryConfig
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
_NA_
OR
> Bump flytestdlib to fix docs issue blocking 1.8 release

- pkg/compiler/validators/typing.go
- pkg/compiler/validators/typing_test.go
This PR makes singular unions castable to their underlying type (ex. `Union[int]` -> `int`)
^^^
fixes https://github.com/flyteorg/flyte/issues/3922
_NA_
> make singular unions castable to their underlying type

- pkg/controller/nodes/task/handler.go
I run two tasks in a workflow, but max Parallelism is being set to 4.
```bash
{"json":{"exec_id":"ahcxqvqbwjs5zczg8d9b","node":"n0","ns":"flytesnacks-development","res_ver":"180043","routine":"worker-2","src":"handler.go:582","tasktype":"python-task","wf":"flytesnacks:development:getting_start.wf"},"level":"info","msg":"Parallelism now set to [1].","ts":"2023-08-29T14:37:15-07:00"}
{"json":{"exec_id":"ahcxqvqbwjs5zczg8d9b","node":"n0","ns":"flytesnacks-development","res_ver":"180043","routine":"worker-2","src":"handler.go:540","tasktype":"python-task","wf":"flytesnacks:development:getting_start.wf"},"level":"info","msg":"Parallelism now set to [2].","ts":"2023-08-29T14:37:15-07:00"}
{"json":{"exec_id":"ahcxqvqbwjs5zczg8d9b","node":"n0","ns":"flytesnacks-development","res_ver":"180043","rou …
```
> Fixing max parallelism

- pkg/controller/controller.go
This PR let PodTemplates read by default.
Remove the condition check for setting the default podTemplates name when starting the informerFactory.
fixes https://github.com/flyteorg/flyte/issues/3946
_NA_
> Read PodTemplates by default.

- pkg/controller/nodes/executor.go
This PR ensures a node fails immediately if the node event returns an `InvalidArgument` exception.
^^^
_NA_
_NA_
> fail immediately on InvalidArgument during node event

- pkg/controller/nodes/node_exec_context.go
As an extension of https://github.com/flyteorg/flytepropeller/pull/596 this adds the non-interruptible switch logic when using the simplified retry behavior.
Part of the https://github.com/flyteorg/flyte/pull/3902 RFC progress.
Does not have tests yet, only as a discussion point.
Discussion topics:
* should we introduce a new variable for the threshold?
Switch to non-interruptible machines when exhausting the retry budget for the new simplified retry behavior.
_NA_
OR
> Feature: Switch to non interrupible when using the simplified retry behavior

- boilerplate/flyte/docker_build/docker_build.sh
- go.mod
- go.sum
- pkg/controller/nodes/subworkflow/launchplan/admin.go
This is the follow-up issue for https://github.com/flyteorg/flytestdlib/pull/164
^^^
_NA_
_NA_
> Bump flytestdlib version

- go.mod
- go.sum
- pkg/controller/nodes/task/plugin_config.go
As title.
Note: Please merge the code below, so that the code will work!
https://github.com/flyteorg/flyteplugins/pull/398
Right now, the agent-service section doesn't need to add supportedTaskTypes anymore.
We can get it by "default-for-task-types" from tasks.
https://github.com/flyteorg/flyteplugins/pull/398
> Add supportTaskTypes for agentservice without write it in config twice.

- pkg/controller/nodes/executor.go
- pkg/controller/nodes/executor_test.go
- pkg/controller/nodes/node_exec_context.go
- pkg/controller/nodes/node_exec_context_test.go
As discussed with @hamersaw this brings the last finishing touches and fixes some one off bugs, see comments below.
> Finish simplify retry behavior PR

- pkg/controller/nodes/task/handler.go
These two ([1](https://github.com/flyteorg/flytepropeller/pull/594) and [2](https://github.com/flyteorg/flytepropeller/pull/611)) changes attempted to fix parallelism computations. However, they introduced additional issues where now if a node in the DAG is visited multiple times in the same round it may count each time towards the parallelism. This PR reverts to previous parallelism computation (which may still be incorrect in certain scenarios).
^^^
_NA_
_NA_
> Reverting to parallelism increases only on non-terminal phase updates
